name: Go Linter

on:
  push:
    branches:
      - "develop"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: "1.20"

      - name: lint
        run:
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

          golangci-lint run
